import type { Metadata } from "next";
import "./globals.css";
import { cn } from "@/lib/utils";
import Navbar from "@/components/Navabar/Navbar";
import Providers from "@/components/Providers";
import { Toaster } from "sonner";
import { cookies } from "next/headers";
import { getServerSideUser } from "@/lib/payload-utils";
import ContextProvider from "@/store/context-provider";
// import { inter, pacifico } from "./fonts";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const nextCookies = cookies();
  const { user } = await getServerSideUser(nextCookies);

  return (
    <html lang="en" className="h-full">
      <body
        className={cn(
          "relative h-full font-sans antialiased"
          // inter.className,
          // pacifico.className
        )}
      >
        <ContextProvider>
          <main className="relative flex flex-col min-h-screen">
            <Providers>
              <div id="modal-hook"></div>
              <div id="backdrop-hook"></div>
              <Navbar user={user} />
              <div className="flex-grow flex-1">{children}</div>
            </Providers>
          </main>
        </ContextProvider>
        <Toaster position="top-center" richColors />
      </body>
    </html>
  );
}
